---
# role: chronyd
# file: molecule/resources/playbooks/converge.yml

- name: "CHRONYD | Converge time service"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
